name: West Shore Physiotherapy
markdown: redcarpet
pygments: true
baseurl: http://ericroberts.github.io/westshorephysio/
exclude:
 - unicorn.rb
 - README.md
 - Procfile
 - Gemfile
 - Gemfile.lock
 - config.ru
 - vendor
